# Travis-CI Build for Boo
# see travis-ci.org for details

language: objective-c

env:
  global:
    # GITHUB_TOKEN=xxxx
    - secure: "eiN8jW3jfxgPm/88aS/JiLLDGMbibbgxUUXoGoBkzBHFV5EEL3hXx5NA7oP07heZG1kvDnsJlRxfQtK5q9X8B0ID7prDc1V3mRfiHHj8/1uiHuIT4RVs3uOlYfE9goZ1nbEgIMA2IDRSAxBs2pmwIFGKy9tKZrL+q/OzCt4Ir7M="
    - EnableNuGetPackageRestore=true
    - NANT_COMMIT="3074f62bdce616058f19c1d6e27bf1bdb1953849"
    - PKG_CONFIG_PATH=/Library/Frameworks/Mono.framework/Versions/Current/lib/pkgconfig/
  matrix:
    - MONO_VER="3.2.3"

install:
  # Obtain mono from a fast mirror (over 150Mb download)
  # - wget "http://switch.dl.sourceforge.net/project/mono.mirror/MonoFramework-MDK-${MONO_VER}.macos10.xamarin.x86.pkg"
  # - wget "http://optimate.dl.sourceforge.net/project/mono.mirror/MonoFramework-MDK-$MONO_VER.macos10.xamarin.x86.pkg"
  - wget "http://hivelocity.dl.sourceforge.net/project/mono.mirror/MonoFramework-MDK-$MONO_VER.macos10.xamarin.x86.pkg"
  # Install mono
  - sudo installer -pkg "MonoFramework-MDK-$MONO_VER.macos10.xamarin.x86.pkg" -target /
  # Fetch a version of NAnt compatible with Mono 3
  - wget --no-check-certificate "https://github.com/nant/nant/archive/$NANT_COMMIT.zip"
  - unzip -qq "$NANT_COMMIT"
  - cd "nant-$NANT_COMMIT"
  - make setup bootstrap/NAnt.exe bootstrap/NAnt.Core.dll bootstrap/NAnt.DotNetTasks.dll
  - cp -r bootstrap ../nant
  - cd -

before_script:
 # Build Boo...
 - mono --runtime=v4.0 nant/NAnt.exe -t:mono-4.0 rebuild
 # MSBuild tasks must be compiled targeting Net 2.0
 - mono --runtime=v4.0 nant/NAnt.exe -t:mono-2.0 Boo.Microsoft.Build.Tasks

script:
 - echo "Running tests not implemented yet :("
 # - nant test

after_success:
 # Generate a simple distribution file
 - cp -r build boo-alpha
 - zip boo-alpha.zip boo-alpha/*
 - mono --debug build/booi.exe scripts/github-release.boo -- alpha boo-alpha.zip

# Notify development list when needed
notifications:
 recipients:
   - boolang@googlegroups.com
 email:
   on_success: change
   on_failure: always
