# Travis-CI Build for Boo
# see travis-ci.org for details

language: c

env:
  global:
    # GITHUB_TOKEN=xxxx
    - secure: "eiN8jW3jfxgPm/88aS/JiLLDGMbibbgxUUXoGoBkzBHFV5EEL3hXx5NA7oP07heZG1kvDnsJlRxfQtK5q9X8B0ID7prDc1V3mRfiHHj8/1uiHuIT4RVs3uOlYfE9goZ1nbEgIMA2IDRSAxBs2pmwIFGKy9tKZrL+q/OzCt4Ir7M="

# Make sure mono is installed
install:
  - echo "Installing Mono... (please wait)"
  # Make sure mono is installed,
  # pipe stdout to dev/null because qq is still too chatty
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get install -qq mono-devel mono-utils nant nunit-console > /dev/null
  # Make sure root certificates are in place
  - mozroots --import --sync > /dev/null

# Run the Build script
script:
 - nant rebuild
 # Running tests does not work :(
 # - nant test
 # Generate a simple distribution file
 - zip boo-alpha.zip build/*
 - mono --debug build/booi.exe scripts/github-release.boo -- alpha boo-alpha.zip

# Notify development list when needed
notifications:
 recipients:
   - boolang@googlegroups.com
 email:
   on_success: change
   on_failure: always
